import { Skeleton } from "~/components/ui/skeleton";

export function FoodTruckListSkeleton() {
	return (
		<div className="space-y-8">
			{Array.from({ length: 10 }).map((_, index) => (
				<Skeleton
					key={`skeleton-${
						// biome-ignore lint/suspicious/noArrayIndexKey: this is an autogenerated array
						index
					}`}
					className="w-full h-28"
				/>
			))}
		</div>
	);
}
